id = "ahoy"
name = "Ahoy"
version = "0.1.0"
schema_version = 1
authors = ["Ahoy Contributors"]
description = "Ahoy language support for Zed"
repository = "https://github.com/yourusername/zed-ahoy"

[grammars.ahoy]
path = "../tree-sitter-ahoy"
