package main

import (
	"fmt"
	"strings"

	"ahoy"
)

// GenerateCWithHotReload generates both a shared library and hot reload host
// Returns: (libraryCode, hostCode)
func GenerateCWithHotReload(ast *ahoy.ASTNode, filename string, enableARC bool, hasRaylib bool, raylibPath string) (string, string) {
	// Generate the normal C code
	normalCode := generateC(ast, filename, enableARC)

	// Transform it into a hot-reloadable library
	libraryCode := transformToLibrary(normalCode, hasRaylib)

	// Generate the host executable
	hostCode := generateHotReloadHost(hasRaylib, raylibPath, filename)

	return libraryCode, hostCode
}

// transformToLibrary converts the generated C code into a shared library
// Key transformations:
// 1. Rename main() to ahoy_game_main(int argc, char** argv)
// 2. Inject hot reload checking into the game loop
// 3. Add global state preservation hooks
// 4. Export necessary symbols
func transformToLibrary(cCode string, hasRaylib bool) string {
	var result strings.Builder

	result.WriteString("/* Hot Reload Library - Auto-generated by Ahoy */\n")
	result.WriteString("/* This file is recompiled on code changes */\n\n")

	// Add hot reload globals at the top
	result.WriteString(`/* Hot Reload Control */
extern volatile int g_ahoy_should_reload;
int ahoy_check_reload(void);

`)

	// Replace main() with ahoy_game_main(int argc, char** argv)
	// Handle both `int main()` and `int main(int argc, char** argv)`
	modifiedCode := cCode
	if strings.Contains(modifiedCode, "int main() {") {
		// No parameters version - add them
		modifiedCode = strings.ReplaceAll(modifiedCode, "int main() {", "int ahoy_game_main(int argc, char** argv) {")
	} else if strings.Contains(modifiedCode, "int main(int argc, char** argv)") {
		// Has parameters - just rename
		modifiedCode = strings.ReplaceAll(modifiedCode, "int main(int argc, char** argv)", "int ahoy_game_main(int argc, char** argv)")
	} else {
		// Fallback - just replace `int main(`
		modifiedCode = strings.ReplaceAll(modifiedCode, "int main(", "int ahoy_game_main(int argc, char** argv, ")
	}

	// Inject reload checking into the game loop
	// Replace `while (!WindowShouldClose())` with a version that checks for reload
	modifiedCode = strings.ReplaceAll(modifiedCode,
		"while (!WindowShouldClose())",
		"while (!WindowShouldClose() && !ahoy_check_reload())")

	// Raylib-specific transformations
	if hasRaylib {
		// Wrap InitWindow to skip on reload
		modifiedCode = strings.ReplaceAll(modifiedCode, 
			"InitWindow(", 
			"ahoy_init_window(")

		// Remove CloseWindow() calls - the host manages window lifecycle
		modifiedCode = strings.ReplaceAll(modifiedCode, "CloseWindow();", "/* CloseWindow(); - managed by hot reload host */")
	}

	// Remove 'const' from global variables to allow hot reload updates
	// This makes constants mutable so new values take effect on reload
	modifiedCode = removeConstFromGlobals(modifiedCode)
	
	// Extract constant initializations for re-initialization after reload
	constantInits := extractConstantInits(modifiedCode)

	// Make ahoy_game_main exported
	modifiedCode = strings.ReplaceAll(modifiedCode,
		"int ahoy_game_main(int argc, char** argv)",
		"__attribute__((visibility(\"default\")))\nint ahoy_game_main(int argc, char** argv)")

	result.WriteString(modifiedCode)

	// Add hot reload state management AFTER the generated code (after all includes)
	result.WriteString(`

/* Hot Reload State Management */
typedef struct AhoyHotReloadState {
    int initialized;
    int window_initialized;  /* Track if Raylib window is open */
    void* user_data;
} AhoyHotReloadState;

static AhoyHotReloadState* g_hot_reload_state = NULL;
volatile int g_ahoy_should_reload = 0;

/* Check if reload is requested */
int ahoy_check_reload(void) {
    return g_ahoy_should_reload;
}
`)

	// Add InitWindow wrapper only for Raylib programs
	if hasRaylib {
		result.WriteString(`
/* Wrapper for InitWindow that skips if already initialized */
void ahoy_init_window(int width, int height, const char* title) {
    if (g_hot_reload_state && g_hot_reload_state->window_initialized) {
        /* Window already open from previous load, skip initialization */
        return;
    }
    
    InitWindow(width, height, title);
    
    if (g_hot_reload_state) {
        g_hot_reload_state->window_initialized = 1;
    }
}
`)
	}

	result.WriteString(`
/* Called by host to request reload */
__attribute__((visibility("default")))
void ahoy_request_reload(void) {
    g_ahoy_should_reload = 1;
}

/* Called by host to clear reload flag */
__attribute__((visibility("default")))
void ahoy_clear_reload(void) {
    g_ahoy_should_reload = 0;
}

/* Called by host to set state pointer */
__attribute__((visibility("default")))
void ahoy_set_state(AhoyHotReloadState* state) {
    g_hot_reload_state = state;
}

/* Called by host to get state pointer */
__attribute__((visibility("default")))
AhoyHotReloadState* ahoy_get_state(void) {
    return g_hot_reload_state;
}

`)

	// Add constant re-initialization function
	if len(constantInits) > 0 {
		result.WriteString(`
/* Re-initialize constants to their new values after reload */
void ahoy_reinit_constants(void) {
`)
		for _, init := range constantInits {
			result.WriteString(init + "\n")
		}
		result.WriteString(`}

`)
	}

	// Add reload notification function
	result.WriteString(`
/* Called after hot reload to reinitialize if needed */
__attribute__((visibility("default")))
void ahoy_on_reload(void) {
    /* Call constant update function if it exists (generated by codegen for getter-based constants) */
    extern void ahoy_update_constants(void) __attribute__((weak));
    if (ahoy_update_constants) {
        ahoy_update_constants();
    }
`)
	
	if len(constantInits) > 0 {
		result.WriteString(`    
    /* Call legacy reinit for backwards compatibility */
    ahoy_reinit_constants();
`)
	}
	
	result.WriteString(`    printf("\033[32m[Hot Reload]\033[0m Code reloaded successfully\n");
}

/* Version string for tracking reloads */
__attribute__((visibility("default")))
const char* ahoy_version = __DATE__ " " __TIME__;
`)

	return result.String()
}

// generateHotReloadHost creates the host executable that watches for changes
// and reloads the library without restarting the window
func generateHotReloadHost(hasRaylib bool, raylibPath string, sourceFile string) string {
	var code strings.Builder

	code.WriteString("/* Hot Reload Host - Auto-generated by Ahoy */\n")
	code.WriteString("/* This executable stays running and reloads your game code */\n\n")

	// Includes
	code.WriteString(`#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dlfcn.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
#include <signal.h>
#include <pthread.h>

`)

	// Hot reload state structure
	code.WriteString(`
/* Hot Reload State Management */
typedef struct AhoyHotReloadState {
    int initialized;
    int window_initialized;
    void* user_data;
} AhoyHotReloadState;

typedef struct {
    void* handle;
    int (*game_main)(int, char**);
    void (*on_reload)(void);
    void (*request_reload)(void);
    void (*clear_reload)(void);
    void (*set_state)(AhoyHotReloadState*);
    AhoyHotReloadState* (*get_state)(void);
    const char* version;
    time_t last_modified;
} GameLibrary;

static GameLibrary g_lib = {0};
static AhoyHotReloadState g_state = {0};
static pthread_mutex_t g_reload_mutex = PTHREAD_MUTEX_INITIALIZER;
static volatile int g_reload_requested = 0;
static volatile int g_running = 1;
static void* g_raylib_handle = NULL;
static int g_has_raylib = 0;  /* Flag to track if this is a Raylib program */

/* Initialize raylib library for hot reload */
int init_raylib_library(void) {`)
	
	// Add raylib initialization based on whether raylib is needed
	if hasRaylib {
		code.WriteString(`
    /* Preload raylib so symbols are available for libgame.so */
    const char* raylib_paths[] = {`)
		
		if raylibPath != "" {
			code.WriteString(fmt.Sprintf(`
        "%s/libraylib.so",`, raylibPath))
		}
		
		code.WriteString(`
        "libraylib.so",
        "/usr/local/lib/libraylib.so",
        "/usr/lib/libraylib.so",
        "/usr/lib/x86_64-linux-gnu/libraylib.so",
        NULL
    };
    
    for (int i = 0; raylib_paths[i] != NULL; i++) {
        g_raylib_handle = dlopen(raylib_paths[i], RTLD_NOW | RTLD_GLOBAL);
        if (g_raylib_handle) {
            printf("\033[32m[Hot Reload]\033[0m Loaded raylib from: %s\n", raylib_paths[i]);
            return 1;
        }
    }
    
    fprintf(stderr, "\033[33m[Hot Reload]\033[0m Warning: Could not preload raylib\n");
    fprintf(stderr, "\033[33m[Hot Reload]\033[0m This may cause symbol resolution issues\n");
    return 0;
`)
	} else {
		code.WriteString(`
    /* No raylib needed */
    return 1;
`)
	}
	
	code.WriteString(`}

/* Get file modification time */
time_t get_file_mtime(const char* path) {
    struct stat st;
    if (stat(path, &st) == 0) {
        return st.st_mtime;
    }
    return 0;
}

/* Load or reload the game library */
int load_game_library(const char* lib_path, int is_reload) {
    time_t current_mtime = get_file_mtime(lib_path);

    if (is_reload && current_mtime <= g_lib.last_modified) {
        return 0; /* No changes */
    }

    pthread_mutex_lock(&g_reload_mutex);

    void* old_handle = NULL;

    if (is_reload && g_lib.handle) {
        printf("\n\033[33m[Hot Reload]\033[0m Detected library change, reloading...\n");

        /* Save state before unloading */
        if (g_lib.get_state) {
            AhoyHotReloadState* lib_state = g_lib.get_state();
            if (lib_state) {
                g_state = *lib_state;
            }
        }

        /* For non-Raylib programs, close old library before loading new one */
        /* This ensures constants are properly updated */
        /* For Raylib programs, keep old library loaded to avoid crashes */
        if (!g_has_raylib) {
            dlclose(g_lib.handle);
            g_lib.handle = NULL;
            usleep(300000); /* 300ms - wait for unload to complete */
        } else {
            old_handle = g_lib.handle;
            g_lib.handle = NULL;
        }

        /* Wait for file to be fully written */
        usleep(250000); /* 250ms */
    }

    /* Try loading the library with retries */
    void* handle = NULL;
    int attempts = 0;
    const int max_attempts = 3;
    
    while (attempts < max_attempts && !handle) {
        if (attempts > 0) {
            usleep(100000 * attempts); /* Exponential backoff: 100ms, 200ms */
        }
        
        handle = dlopen(lib_path, RTLD_NOW | RTLD_GLOBAL);
        if (!handle) {
            attempts++;
            if (attempts < max_attempts) {
                /* Wait and retry */
                continue;
            }
            fprintf(stderr, "\033[31m[Hot Reload]\033[0m Error loading library after %d attempts: %s\n", 
                    max_attempts, dlerror());
            
            /* Try to restore old handle if we have one (Raylib case) */
            if (old_handle) {
                fprintf(stderr, "\033[33m[Hot Reload]\033[0m Keeping previous library version\n");
                g_lib.handle = old_handle;
                pthread_mutex_unlock(&g_reload_mutex);
                return -1;
            }
            
            fprintf(stderr, "\033[31m[Hot Reload]\033[0m Fatal: Cannot continue without library\n");
            pthread_mutex_unlock(&g_reload_mutex);
            exit(1);
        }
    }

    /* Clear any existing error */
    dlerror();

    /* Load function pointers */
    int (*game_main)(int, char**) = dlsym(handle, "ahoy_game_main");
    void (*on_reload)(void) = dlsym(handle, "ahoy_on_reload");
    void (*request_reload)(void) = dlsym(handle, "ahoy_request_reload");
    void (*clear_reload)(void) = dlsym(handle, "ahoy_clear_reload");
    void (*set_state)(AhoyHotReloadState*) = dlsym(handle, "ahoy_set_state");
    AhoyHotReloadState* (*get_state)(void) = dlsym(handle, "ahoy_get_state");
    const char* version = (const char*)dlsym(handle, "ahoy_version");

    const char* dl_error = dlerror();
    if (dl_error || !game_main) {
        fprintf(stderr, "\033[31m[Hot Reload]\033[0m Error: ahoy_game_main not found: %s\n",
                dl_error ? dl_error : "symbol not found");
        dlclose(handle);
        
        /* Try to restore old handle if we have one (Raylib case) */
        if (old_handle) {
            fprintf(stderr, "\033[33m[Hot Reload]\033[0m Keeping previous library version\n");
            g_lib.handle = old_handle;
            pthread_mutex_unlock(&g_reload_mutex);
            return -1;
        }
        
        fprintf(stderr, "\033[31m[Hot Reload]\033[0m Fatal: Cannot continue without game_main\n");
        pthread_mutex_unlock(&g_reload_mutex);
        exit(1);
    }

    /* New library loaded successfully - close old one if we kept it (Raylib case) */
    if (old_handle) {
        dlclose(old_handle);
    }

    g_lib.handle = handle;
    g_lib.game_main = game_main;
    g_lib.on_reload = on_reload;
    g_lib.request_reload = request_reload;
    g_lib.clear_reload = clear_reload;
    g_lib.set_state = set_state;
    g_lib.get_state = get_state;
    g_lib.version = version;
    g_lib.last_modified = current_mtime;

    /* Restore state */
    if (g_lib.set_state) {
        g_lib.set_state(&g_state);
    }

    /* Clear the reload flag in the new library */
    if (g_lib.clear_reload) {
        g_lib.clear_reload();
    }

    if (is_reload && g_lib.on_reload) {
        g_lib.on_reload();
    }

    if (!is_reload) {
        printf("\033[32m[Hot Reload]\033[0m Initial library loaded\n");
        if (g_lib.version) {
            printf("\033[32m[Hot Reload]\033[0m Version: %s\n", g_lib.version);
        }
    } else {
        printf("\033[32m[Hot Reload]\033[0m ✓ Reload complete\n");
    }

    pthread_mutex_unlock(&g_reload_mutex);
    return 1;
}

/* File watcher thread */
void* file_watcher_thread(void* arg) {
    const char* lib_path = (const char*)arg;

    while (g_running) {
        sleep(1); /* Check every second */

        time_t current_mtime = get_file_mtime(lib_path);

        pthread_mutex_lock(&g_reload_mutex);
        if (current_mtime > g_lib.last_modified) {
            /* New library version available - signal the game to exit its loop */
            if (g_lib.request_reload) {
                g_lib.request_reload();
                g_reload_requested = 1;
            }
        }
        pthread_mutex_unlock(&g_reload_mutex);
    }

    return NULL;
}

/* Signal handler for graceful shutdown */
void signal_handler(int sig) {
    if (sig == SIGINT || sig == SIGTERM) {
        printf("\n\033[33m[Hot Reload]\033[0m Shutting down...\n");
        g_running = 0;
    }
}

`)

	// Main function - different for Raylib vs non-Raylib
	if hasRaylib {
		// Raylib version - run game in a loop, reloading when requested
		code.WriteString(fmt.Sprintf(`
int main(int argc, char** argv) {
    const char* lib_path = "./output/libgame.so";
    const char* source_path = "%s";
    pthread_t watcher_thread;

    g_has_raylib = 1;  /* Mark as Raylib program for special reload handling */

    signal(SIGINT, signal_handler);
    signal(SIGTERM, signal_handler);

    printf("\033[1;36m╔════════════════════════════════════════╗\033[0m\n");
    printf("\033[1;36m║     Ahoy Hot Reload Development      ║\033[0m\n");
    printf("\033[1;36m╚════════════════════════════════════════╝\033[0m\n");
    printf("\033[32m[Hot Reload]\033[0m Watching: %%s\n", source_path);
    printf("\033[32m[Hot Reload]\033[0m Library: %%s\n", lib_path);
    printf("\033[32m[Hot Reload]\033[0m Edit your code and save to see changes!\n");
    printf("\033[32m[Hot Reload]\033[0m Press Ctrl+C to exit\n\n");

    /* Initialize raylib library */
    init_raylib_library();

    /* Initial load */
    if (load_game_library(lib_path, 0) < 0) {
        fprintf(stderr, "Failed to load initial library\n");
        return 1;
    }

    /* Start file watcher thread */
    pthread_create(&watcher_thread, NULL, file_watcher_thread, (void*)lib_path);

    /* Game reload loop */
    while (g_running) {
        g_reload_requested = 0;

        /* Run the game - it will exit when reload is requested or window closes */
        if (g_lib.game_main) {
            g_lib.game_main(argc, argv);
        }

        /* Check if we should reload or exit */
        if (!g_running) {
            break; /* User pressed Ctrl+C */
        }

        if (g_reload_requested) {
            /* Reload the library */
            printf("\n\033[33m[Hot Reload]\033[0m Reloading library...\n");

            if (load_game_library(lib_path, 1) < 0) {
                fprintf(stderr, "\033[31m[Hot Reload]\033[0m Reload failed, exiting\n");
                break;
            }

            printf("\033[32m[Hot Reload]\033[0m Restarting game...\n\n");
            /* Loop continues, will call game_main again with new library */
        } else {
            /* Window was closed normally, exit */
            break;
        }
    }

    /* Cleanup */
    g_running = 0;
    pthread_join(watcher_thread, NULL);

    if (g_lib.handle) {
        dlclose(g_lib.handle);
    }

    /* Close the Raylib window if it's still open */
    if (g_raylib_handle) {
        /* Get CloseWindow function from raylib */
        typedef int (*IsWindowReadyFunc)(void);
        typedef void (*CloseWindowFunc)(void);
        
        IsWindowReadyFunc IsWindowReady = (IsWindowReadyFunc)dlsym(g_raylib_handle, "IsWindowReady");
        CloseWindowFunc CloseWindow = (CloseWindowFunc)dlsym(g_raylib_handle, "CloseWindow");
        
        if (IsWindowReady && CloseWindow && IsWindowReady()) {
            CloseWindow();
        }
        
        dlclose(g_raylib_handle);
    }

    printf("\n\033[32m[Hot Reload]\033[0m Shutdown complete\n");
    return 0;
}
`, sourceFile))
	} else {
		// Non-raylib version
		code.WriteString(`
int main(int argc, char** argv) {
    const char* lib_path = "./output/libgame.so";
    pthread_t watcher_thread;

    signal(SIGINT, signal_handler);
    signal(SIGTERM, signal_handler);

    printf("\033[1;36m╔════════════════════════════════════════╗\033[0m\n");
    printf("\033[1;36m║     Ahoy Hot Reload Development      ║\033[0m\n");
    printf("\033[1;36m╚════════════════════════════════════════╝\033[0m\n");

    /* Initialize raylib library */
    init_raylib_library();

    /* Initial load */
    if (load_game_library(lib_path, 0) < 0) {
        return 1;
    }

    /* Start file watcher thread */
    pthread_create(&watcher_thread, NULL, file_watcher_thread, (void*)lib_path);

    /* Main loop */
    while (g_running) {
        if (g_reload_requested) {
            g_reload_requested = 0;
            printf("\033[33m[Hot Reload]\033[0m Reloading library...\n");
            
            if (load_game_library(lib_path, 1) < 0) {
                fprintf(stderr, "\033[31m[Hot Reload]\033[0m Reload failed, continuing with old version\n");
            } else {
                printf("\033[32m[Hot Reload]\033[0m Rerunning game...\n");
            }
        }

        if (g_lib.game_main) {
            g_lib.game_main(argc, argv);
        }

        sleep(1);
    }

    /* Cleanup */
    pthread_join(watcher_thread, NULL);

    if (g_lib.handle) {
        dlclose(g_lib.handle);
    }

    if (g_raylib_handle) {
        dlclose(g_raylib_handle);
    }

    return 0;
}
`)
	}

	return code.String()
}

// removeConstFromGlobals removes 'const' keyword from global variable declarations
// This allows constants to be updated when the library is reloaded with new values
// Returns: (modified code, list of constant initializations)
func removeConstFromGlobals(code string) string {
	lines := strings.Split(code, "\n")
	var result []string
	
	inFunction := false
	braceCount := 0
	
	for _, line := range lines {
		// Track if we're inside a function
		braceCount += strings.Count(line, "{")
		braceCount -= strings.Count(line, "}")
		
		// Check for function definitions
		if strings.Contains(line, "(") && strings.Contains(line, ")") && strings.Contains(line, "{") {
			inFunction = true
		}
		if braceCount == 0 {
			inFunction = false
		}
		
		// Only modify const declarations at global scope (not in functions)
		// Match patterns like: const int X = 5; or const char* X = "hello";
		if !inFunction && strings.HasPrefix(strings.TrimSpace(line), "const ") {
			// Remove 'const ' from the beginning
			line = strings.Replace(line, "const ", "", 1)
		}
		
		result = append(result, line)
	}
	
	return strings.Join(result, "\n")
}

// extractConstantInits extracts global constant initialization statements
// from the generated C code for hot reload re-initialization
func extractConstantInits(code string) []string {
	lines := strings.Split(code, "\n")
	var inits []string
	
	inFunction := false
	braceCount := 0
	inCommentBlock := false
	
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		
		// Skip comments
		if strings.HasPrefix(trimmed, "/*") {
			inCommentBlock = true
		}
		if strings.HasSuffix(trimmed, "*/") {
			inCommentBlock = false
			continue
		}
		if inCommentBlock || strings.HasPrefix(trimmed, "//") {
			continue
		}
		
		// Track if we're inside a function
		braceCount += strings.Count(line, "{")
		braceCount -= strings.Count(line, "}")
		
		// Check for function definitions
		if strings.Contains(line, "(") && strings.Contains(line, ")") && strings.Contains(line, "{") {
			inFunction = true
		}
		if braceCount == 0 {
			inFunction = false
		}
		
		// Look for global variable declarations with initialization
		// Pattern: type name = value;
		// Already had 'const' removed, so looking for simple assignments
		if !inFunction && strings.Contains(trimmed, "=") && strings.HasSuffix(trimmed, ";") {
			// Skip if it's a typedef, struct, enum, or function pointer
			if strings.HasPrefix(trimmed, "typedef") || 
			   strings.HasPrefix(trimmed, "struct") ||
			   strings.HasPrefix(trimmed, "enum") ||
			   strings.Contains(trimmed, "(*") {
				continue
			}
			
			// Skip extern declarations
			if strings.HasPrefix(trimmed, "extern") {
				continue
			}
			
			// Extract the assignment part (name = value;)
			// Find the variable name and value
			parts := strings.SplitN(trimmed, "=", 2)
			if len(parts) == 2 {
				// Get the variable name (last word before =)
				leftParts := strings.Fields(strings.TrimSpace(parts[0]))
				if len(leftParts) > 0 {
					varName := leftParts[len(leftParts)-1]
					// Handle pointer types (e.g., "char*" -> remove *)
					varName = strings.TrimRight(varName, "*")
					value := strings.TrimSpace(parts[1])
					
					// Generate re-initialization statement
					inits = append(inits, fmt.Sprintf("    %s = %s", varName, value))
				}
			}
		}
	}
	
	return inits
}
