package main

import (
	"fmt"
	"strings"

	"ahoy"
)

// GenerateCWithHotReload generates both a shared library and hot reload host
// Returns: (libraryCode, hostCode)
func GenerateCWithHotReload(ast *ahoy.ASTNode, filename string, enableARC bool, hasRaylib bool, raylibPath string) (string, string) {
	// Generate the normal C code
	normalCode := generateC(ast, filename, enableARC)

	// Transform it into a hot-reloadable library
	libraryCode := transformToLibrary(normalCode)

	// Generate the host executable
	hostCode := generateHotReloadHost(hasRaylib, raylibPath, filename)

	return libraryCode, hostCode
}

// transformToLibrary converts the generated C code into a shared library
// Key transformations:
// 1. Rename main() to ahoy_game_main(int argc, char** argv)
// 2. Inject hot reload checking into the game loop
// 3. Add global state preservation hooks
// 4. Export necessary symbols
func transformToLibrary(cCode string) string {
	var result strings.Builder

	result.WriteString("/* Hot Reload Library - Auto-generated by Ahoy */\n")
	result.WriteString("/* This file is recompiled on code changes */\n\n")

	// Add hot reload globals at the top
	result.WriteString(`/* Hot Reload Control */
extern volatile int g_ahoy_should_reload;
int ahoy_check_reload(void);

`)

	// Replace main() with ahoy_game_main(int argc, char** argv)
	// Handle both `int main()` and `int main(int argc, char** argv)`
	modifiedCode := cCode
	if strings.Contains(modifiedCode, "int main() {") {
		// No parameters version - add them
		modifiedCode = strings.ReplaceAll(modifiedCode, "int main() {", "int ahoy_game_main(int argc, char** argv) {")
	} else if strings.Contains(modifiedCode, "int main(int argc, char** argv)") {
		// Has parameters - just rename
		modifiedCode = strings.ReplaceAll(modifiedCode, "int main(int argc, char** argv)", "int ahoy_game_main(int argc, char** argv)")
	} else {
		// Fallback - just replace `int main(`
		modifiedCode = strings.ReplaceAll(modifiedCode, "int main(", "int ahoy_game_main(int argc, char** argv, ")
	}

	// Inject reload checking into the game loop
	// Replace `while (!WindowShouldClose())` with a version that checks for reload
	modifiedCode = strings.ReplaceAll(modifiedCode,
		"while (!WindowShouldClose())",
		"while (!WindowShouldClose() && !ahoy_check_reload())")

	// Make ahoy_game_main exported
	modifiedCode = strings.ReplaceAll(modifiedCode,
		"int ahoy_game_main(int argc, char** argv)",
		"__attribute__((visibility(\"default\")))\nint ahoy_game_main(int argc, char** argv)")

	result.WriteString(modifiedCode)

	// Add hot reload state management AFTER the generated code (after all includes)
	result.WriteString(`

/* Hot Reload State Management */
typedef struct AhoyHotReloadState {
    int initialized;
    void* user_data;
} AhoyHotReloadState;

static AhoyHotReloadState* g_hot_reload_state = NULL;
volatile int g_ahoy_should_reload = 0;

/* Check if reload is requested */
int ahoy_check_reload(void) {
    return g_ahoy_should_reload;
}

/* Called by host to request reload */
__attribute__((visibility("default")))
void ahoy_request_reload(void) {
    g_ahoy_should_reload = 1;
}

/* Called by host to set state pointer */
__attribute__((visibility("default")))
void ahoy_set_state(AhoyHotReloadState* state) {
    g_hot_reload_state = state;
}

/* Called by host to get state pointer */
__attribute__((visibility("default")))
AhoyHotReloadState* ahoy_get_state(void) {
    return g_hot_reload_state;
}

`)

	// Add reload notification function
	result.WriteString(`

/* Called after hot reload to reinitialize if needed */
__attribute__((visibility("default")))
void ahoy_on_reload(void) {
    printf("\033[32m[Hot Reload]\033[0m Code reloaded successfully\n");
}

/* Version string for tracking reloads */
__attribute__((visibility("default")))
const char* ahoy_version = __DATE__ " " __TIME__;
`)

	return result.String()
}

// generateHotReloadHost creates the host executable that watches for changes
// and reloads the library without restarting the window
func generateHotReloadHost(hasRaylib bool, raylibPath string, sourceFile string) string {
	var code strings.Builder

	code.WriteString("/* Hot Reload Host - Auto-generated by Ahoy */\n")
	code.WriteString("/* This executable stays running and reloads your game code */\n\n")

	// Includes
	code.WriteString(`#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dlfcn.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
#include <signal.h>
#include <pthread.h>

`)

	// Hot reload state structure
	code.WriteString(`
/* Hot Reload State Management */
typedef struct AhoyHotReloadState {
    int initialized;
    void* user_data;
} AhoyHotReloadState;

typedef struct {
    void* handle;
    int (*game_main)(int, char**);
    void (*on_reload)(void);
    void (*request_reload)(void);
    void (*set_state)(AhoyHotReloadState*);
    AhoyHotReloadState* (*get_state)(void);
    const char** version;
    time_t last_modified;
} GameLibrary;

static GameLibrary g_lib = {0};
static AhoyHotReloadState g_state = {0};
static pthread_mutex_t g_reload_mutex = PTHREAD_MUTEX_INITIALIZER;
static volatile int g_reload_requested = 0;
static volatile int g_running = 1;

/* Get file modification time */
time_t get_file_mtime(const char* path) {
    struct stat st;
    if (stat(path, &st) == 0) {
        return st.st_mtime;
    }
    return 0;
}

/* Load or reload the game library */
int load_game_library(const char* lib_path, int is_reload) {
    time_t current_mtime = get_file_mtime(lib_path);

    if (is_reload && current_mtime <= g_lib.last_modified) {
        return 0; /* No changes */
    }

    pthread_mutex_lock(&g_reload_mutex);

    if (is_reload && g_lib.handle) {
        printf("\n\033[33m[Hot Reload]\033[0m Detected library change, reloading...\n");

        /* Save state before unloading */
        if (g_lib.get_state) {
            AhoyHotReloadState* lib_state = g_lib.get_state();
            if (lib_state) {
                g_state = *lib_state;
            }
        }

        dlclose(g_lib.handle);
        g_lib.handle = NULL;

        /* Wait for file to be fully written */
        usleep(150000); /* 150ms */
    }

    /* Load the library */
    void* handle = dlopen(lib_path, RTLD_NOW | RTLD_LOCAL);
    if (!handle) {
        fprintf(stderr, "\033[31m[Hot Reload]\033[0m Error loading library: %s\n", dlerror());
        pthread_mutex_unlock(&g_reload_mutex);
        return -1;
    }

    /* Clear any existing error */
    dlerror();

    /* Load function pointers */
    int (*game_main)(int, char**) = dlsym(handle, "ahoy_game_main");
    void (*on_reload)(void) = dlsym(handle, "ahoy_on_reload");
    void (*request_reload)(void) = dlsym(handle, "ahoy_request_reload");
    void (*set_state)(AhoyHotReloadState*) = dlsym(handle, "ahoy_set_state");
    AhoyHotReloadState* (*get_state)(void) = dlsym(handle, "ahoy_get_state");
    const char** version = (const char**)dlsym(handle, "ahoy_version");

    const char* dl_error = dlerror();
    if (dl_error || !game_main) {
        fprintf(stderr, "\033[31m[Hot Reload]\033[0m Error: ahoy_game_main not found: %s\n",
                dl_error ? dl_error : "symbol not found");
        dlclose(handle);
        pthread_mutex_unlock(&g_reload_mutex);
        return -1;
    }

    g_lib.handle = handle;
    g_lib.game_main = game_main;
    g_lib.on_reload = on_reload;
    g_lib.request_reload = request_reload;
    g_lib.set_state = set_state;
    g_lib.get_state = get_state;
    g_lib.version = version;
    g_lib.last_modified = current_mtime;

    /* Restore state */
    if (g_lib.set_state) {
        g_lib.set_state(&g_state);
    }

    if (is_reload && g_lib.on_reload) {
        g_lib.on_reload();
    }

    if (!is_reload) {
        printf("\033[32m[Hot Reload]\033[0m Initial library loaded\n");
        if (g_lib.version && *g_lib.version) {
            printf("\033[32m[Hot Reload]\033[0m Version: %s\n", *g_lib.version);
        }
    } else {
        printf("\033[32m[Hot Reload]\033[0m ✓ Reload complete\n");
    }

    pthread_mutex_unlock(&g_reload_mutex);
    return 1;
}

/* File watcher thread */
void* file_watcher_thread(void* arg) {
    const char* lib_path = (const char*)arg;

    while (g_running) {
        sleep(1); /* Check every second */

        time_t current_mtime = get_file_mtime(lib_path);

        pthread_mutex_lock(&g_reload_mutex);
        if (current_mtime > g_lib.last_modified) {
            /* New library version available - signal the game to exit its loop */
            if (g_lib.request_reload) {
                g_lib.request_reload();
                g_reload_requested = 1;
            }
        }
        pthread_mutex_unlock(&g_reload_mutex);
    }

    return NULL;
}

/* Signal handler for graceful shutdown */
void signal_handler(int sig) {
    if (sig == SIGINT || sig == SIGTERM) {
        printf("\n\033[33m[Hot Reload]\033[0m Shutting down...\n");
        g_running = 0;
    }
}

`)

	// Main function - different for Raylib vs non-Raylib
	if hasRaylib {
		// Raylib version - run game in a loop, reloading when requested
		code.WriteString(fmt.Sprintf(`
int main(int argc, char** argv) {
    const char* lib_path = "./output/libgame.so";
    const char* source_path = "%s";
    pthread_t watcher_thread;

    signal(SIGINT, signal_handler);
    signal(SIGTERM, signal_handler);

    printf("\033[1;36m╔════════════════════════════════════════╗\033[0m\n");
    printf("\033[1;36m║     Ahoy Hot Reload Development      ║\033[0m\n");
    printf("\033[1;36m╚════════════════════════════════════════╝\033[0m\n");
    printf("\033[32m[Hot Reload]\033[0m Watching: %%s\n", source_path);
    printf("\033[32m[Hot Reload]\033[0m Library: %%s\n", lib_path);
    printf("\033[32m[Hot Reload]\033[0m Edit your code and save to see changes!\n");
    printf("\033[32m[Hot Reload]\033[0m Press Ctrl+C to exit\n\n");

    /* Initial load */
    if (load_game_library(lib_path, 0) < 0) {
        fprintf(stderr, "Failed to load initial library\n");
        return 1;
    }

    /* Start file watcher thread */
    pthread_create(&watcher_thread, NULL, file_watcher_thread, (void*)lib_path);

    /* Game reload loop */
    while (g_running) {
        g_reload_requested = 0;

        /* Run the game - it will exit when reload is requested or window closes */
        if (g_lib.game_main) {
            g_lib.game_main(argc, argv);
        }

        /* Check if we should reload or exit */
        if (!g_running) {
            break; /* User pressed Ctrl+C */
        }

        if (g_reload_requested) {
            /* Reload the library */
            printf("\n\033[33m[Hot Reload]\033[0m Reloading library...\n");

            if (load_game_library(lib_path, 1) < 0) {
                fprintf(stderr, "\033[31m[Hot Reload]\033[0m Reload failed, exiting\n");
                break;
            }

            printf("\033[32m[Hot Reload]\033[0m Restarting game...\n\n");
            /* Loop continues, will call game_main again with new library */
        } else {
            /* Window was closed normally, exit */
            break;
        }
    }

    /* Cleanup */
    g_running = 0;
    pthread_join(watcher_thread, NULL);

    if (g_lib.handle) {
        dlclose(g_lib.handle);
    }

    printf("\n\033[32m[Hot Reload]\033[0m Shutdown complete\n");
    return 0;
}
`, sourceFile))
	} else {
		// Non-raylib version
		code.WriteString(`
int main(int argc, char** argv) {
    const char* lib_path = "./output/libgame.so";
    pthread_t watcher_thread;

    signal(SIGINT, signal_handler);
    signal(SIGTERM, signal_handler);

    printf("\033[1;36m╔════════════════════════════════════════╗\033[0m\n");
    printf("\033[1;36m║     Ahoy Hot Reload Development      ║\033[0m\n");
    printf("\033[1;36m╚════════════════════════════════════════╝\033[0m\n");

    /* Initial load */
    if (load_game_library(lib_path, 0) < 0) {
        return 1;
    }

    /* Start file watcher thread */
    pthread_create(&watcher_thread, NULL, file_watcher_thread, (void*)lib_path);

    /* Main loop */
    while (g_running) {
        if (g_reload_requested) {
            g_reload_requested = 0;
            printf("\033[33m[Hot Reload]\033[0m Rerunning game...\n");
        }

        if (g_lib.game_main) {
            g_lib.game_main(argc, argv);
        }

        sleep(1);
    }

    /* Cleanup */
    pthread_join(watcher_thread, NULL);

    if (g_lib.handle) {
        dlclose(g_lib.handle);
    }

    return 0;
}
`)
	}

	return code.String()
}
